# Generated by Django 4.2 on 2023-06-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('dias_trabajo', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=15)),
                ('horario_entrada', models.CharField(max_length=15)),
                ('horario_salida', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.empleado')),
            ],
        ),
    ]
